version: "3.9"
services:
  renterd:
    image: ghcr.io/siafoundation/renterd:master
    environment:
      - RENTERD_SEED=${SEED}
      - RENTERD_API_PASSWORD=${API_PASSWORD}
      - RENTERD_NETWORK=${RENTERD_NETWORK}
    ports:
      - 9980:9980
      - 9981:9981
      - 8080:8080
    volumes:
      - ./data:/data
    restart: unless-stopped
    stop_grace_period: 5m
  walletd:
    image: ghcr.io/siafoundation/walletd:latest
    environment:
      - WALLETD_API_PASSWORD=${API_PASSWORD}
      - WALLETD_CONFIG_FILE=/data/config.yml
    ports:
      - 127.0.0.1:9780:9980/tcp
      - 9781:9981/tcp
    volumes:
      - ./data:/data
    restart: unless-stopped
  hostd:
    image: ghcr.io/siafoundation/hostd:latest
    environment:
      - HOSTD_SEED=${SEED}
      - HOSTD_API_PASSWORD=${API_PASSWORD}
      - HOSTD_CONFIG_FILE=/data/config.yml
    ports:
      - 127.0.0.1:9880:9980/tcp
      - 9881-9883:9981-9983/tcp
    volumes:
      - ./data:/data
      - ./storage:/storage
    restart: unless-stopped