version: "3.9"
services:
  hostd:
    image: ghcr.io/siafoundation/hostd:latest
    environment:
      - HOSTD_SEED=real ready harbor jungle cycle romance border lucky budget mention armor spatial
      - HOSTD_API_PASSWORD=test
    ports:
      - 127.0.0.1:9880:9980/tcp
      - 9881-9883:9981-9983/tcp
    volumes:
      - ./data:/data
      - ./data:/storage
    restart: unless-stopped
  renterd:
    image: ghcr.io/siafoundation/renterd:master
    environment:
      - RENTERD_SEED=real ready harbor jungle cycle romance border lucky budget mention armor spatial
      - RENTERD_API_PASSWORD=test
      - RENTERD_NETWORK=zen
    ports:
      - 9980:9980
      - 9981:9981
      - 8080:8080
    volumes:
      - ./data:/data
    restart: unless-stopped
    stop_grace_period: 5m
  walletd:
    image: ghcr.io/siafoundation/walletd:latest
    environment:
      - WALLETD_API_PASSWORD=test
      - WALLETD_NETWORK=testnet
    ports:
      - 127.0.0.1:9780:9980/tcp
      - 9781:9981/tcp
    volumes:
      - ./data:/data
    restart: unless-stopped